
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 14 22:36:12 CST 2020
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int NUMERO = 27;
  public static final int ACUMULAR = 20;
  public static final int TIPO = 34;
  public static final int NOMBRE = 28;
  public static final int LLAVES_C = 8;
  public static final int FACIL = 36;
  public static final int LLAVES_A = 7;
  public static final int PLANETAS = 10;
  public static final int DOS_PUNTOS = 4;
  public static final int NEUTRALES = 21;
  public static final int DIFICIL = 37;
  public static final int CORCHE_C = 3;
  public static final int MAPA = 9;
  public static final int IDENTIFICADOR = 26;
  public static final int CORCHE_A = 2;
  public static final int TAMANO = 14;
  public static final int PLANETAS_JUGADOR = 33;
  public static final int PLANET_NEU = 18;
  public static final int NICK_NAME = 31;
  public static final int ID = 13;
  public static final int MOSTRAR_NAVES = 22;
  public static final int EOF = 0;
  public static final int TRUE = 38;
  public static final int COMILLAS = 6;
  public static final int PALABRA = 32;
  public static final int error = 1;
  public static final int COMA = 5;
  public static final int PLANETAS_NEUTRALES = 11;
  public static final int MOSTRAR_ESTADISTICAS = 23;
  public static final int PORCENTAJE_MUERTES = 30;
  public static final int HUMANO = 35;
  public static final int FINALIZACION = 25;
  public static final int MAPA_CIEGO = 19;
  public static final int JUGADORES = 12;
  public static final int PRODUCCION = 24;
  public static final int COLUMNAS = 16;
  public static final int FALSE = 39;
  public static final int ALAZAR = 17;
  public static final int FILAS = 15;
  public static final int NAVES = 29;
}

