
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 24 23:51:17 CST 2020
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class SimbolosJugador {
  /* terminals */
  public static final int error = 1;
  public static final int NOMBRE = 2;
  public static final int EOF = 0;
}

