
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 28 23:05:03 CST 2020
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class SimbolosNick {
  /* terminals */
  public static final int ERR = 3;
  public static final int error = 1;
  public static final int NICK = 2;
  public static final int EOF = 0;
}

