
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 28 23:09:38 CST 2020
//----------------------------------------------------

package replay;

/** CUP generated class containing symbol constants. */
public class SimbolosR {
  /* terminals */
  public static final int TURNO_LLEGADA = 51;
  public static final int NUMERO = 27;
  public static final int ACUMULAR = 20;
  public static final int TURNO_NUMERO = 28;
  public static final int TIPO = 39;
  public static final int TURNO = 52;
  public static final int NOMBRE = 29;
  public static final int LLAVES_C = 8;
  public static final int FACIL = 41;
  public static final int LLAVES_A = 7;
  public static final int PLANETAS = 10;
  public static final int DOS_PUNTOS = 4;
  public static final int NEUTRALES = 21;
  public static final int DIFICIL = 42;
  public static final int CORCHE_C = 3;
  public static final int MAPA = 9;
  public static final int IDENTIFICADOR = 26;
  public static final int CORCHE_A = 2;
  public static final int COORDENADA_Y = 35;
  public static final int COORDENADA_X = 34;
  public static final int NAVES_ENVIADAS = 36;
  public static final int TAMANO = 14;
  public static final int PLANETAS_JUGADOR = 38;
  public static final int NOMBRE_JUG = 53;
  public static final int PLANET_NEU = 18;
  public static final int NICK_NAME = 32;
  public static final int ID = 13;
  public static final int MENSAJES = 46;
  public static final int MOSTRAR_NAVES = 22;
  public static final int EOF = 0;
  public static final int TRUE = 43;
  public static final int COMILLAS = 6;
  public static final int PALABRA = 33;
  public static final int error = 1;
  public static final int RESULTADO = 54;
  public static final int COMA = 5;
  public static final int PLANETAS_NEUTRALES = 11;
  public static final int TURNO_JUGADOR = 50;
  public static final int MOSTRAR_ESTADISTICAS = 23;
  public static final int TIPOPLANETA = 49;
  public static final int PORCENTAJE_MUERTES = 31;
  public static final int HUMANO = 40;
  public static final int REPETICION = 45;
  public static final int FINALIZACION = 25;
  public static final int ORIGEN = 47;
  public static final int JUGADOR = 37;
  public static final int MAPA_CIEGO = 19;
  public static final int COORDENADAY = 56;
  public static final int DESTINO = 48;
  public static final int JUGADORES = 12;
  public static final int COORDENADAX = 55;
  public static final int PRODUCCION = 24;
  public static final int COLUMNAS = 16;
  public static final int FALSE = 44;
  public static final int ALAZAR = 17;
  public static final int FILAS = 15;
  public static final int NAVES = 30;
}

